### ISSUE TITLE
Questions about the final weight addition

### ISSUE THREAD

**Issue by StuZh** [AviSoori1x/makeMoE#2]
`final_output.masked_scatter_(expert_mask.unsqueeze(-1), weighted_output)`
This code seems to cause the output of the next traversed expert to overwrite the output of the previous expert, shouldn't it be added?

**Comment by AviSoori1x** [comment]
Hey @StuZh, Thank you for pointing this out. I tried to be too clever and got it wrong. 
I swapped that line with this:
`# Update final output additively by indexing and adding
   final_output[expert_mask] += weighted_output.squeeze(1)`
This is the expected behavior

**Comment by AviSoori1x** [comment]
feel free to reopen if something else needs to be fixed. Thanks!
