### ISSUE TITLE
squeeze(1) in weighted_output.squeeze(1) doesn't seem to work

### ISSUE THREAD

**Issue by mst272** [AviSoori1x/makeMoE#4]
Thank you very much for your article and code, it is very helpful for my study.

But I found a problem，in the class SparseMoE:
`final_output[expert_mask] += weighted_output.squeeze(1)`

squeeze(1) in weighted_output.squeeze(1) doesn't seem to work, the results are the same whether or not squeeze(1) is used.
So I'm wondering why use it?

**Comment by AviSoori1x** [comment]
Hi, Thanks! I believe this was a remnant from one of my previous trials of getting the masking right but this somehow escaped my attention. Let me remove it.
